.gitignore
src/collections/dlist.rs
src/policies/lru.rs
src/policies/mod.rs

feat: inroduce lru policy

---

Cargo.lock
Cargo.toml
src/collections/dlist.rs
src/policies/lru.rs
src/policies/mod.rs
src/policies/tinylfu.rs

feat: introduce TinyLfu eviction policy

---

src/lib.rs
src/policies/lru.rs
src/policies/mod.rs
src/policies/tinylfu.rs

feat: introduce generic policy

---

Cargo.lock
src/container.rs
src/lib.rs
src/policies/lru.rs
src/policies/mod.rs
src/policies/tinylfu.rs
src/store/mod.rs

feat: introduce container framework

---

src/container.rs

test: add simple test for container

---

foyer-bench/src/main.rs
foyer/src/container.rs
foyer/src/policies/mod.rs
foyer/src/store/mod.rs

fix: fix bug with bench

---

Cargo.lock
foyer/Cargo.toml
foyer/src/container.rs
foyer/src/store/read_only_file_store.rs

feat: add log support

---

Cargo.lock
foyer-storage-bench/src/main.rs
foyer-storage/Cargo.toml
foyer-storage/src/device/fs.rs
foyer-storage/src/device/mod.rs
foyer-storage/src/flusher.rs
foyer-storage/src/reclaimer.rs
foyer-storage/src/region.rs
foyer-storage/src/region_manager.rs
foyer-storage/src/store.rs

feat: impl storage recovery

---

foyer/src/lib.rs

fix: export extern crate

---

foyer/src/lib.rs

Revert "fix: export extern crate"

---

foyer-storage/src/device/fs.rs

fix: disable O_DIRECT on non-linux targets

---

foyer-storage/src/lib.rs

chore: export storage config

---

foyer-storage/src/admission.rs
foyer-storage/src/reinsertion.rs

chore: AdmitAll & ReinsertNone no longer requires KV default

---

foyer-storage/src/store.rs

fix: recovery test

---

foyer-storage-bench/src/main.rs
foyer-storage/src/flusher.rs
foyer-storage/src/lib.rs
foyer-storage/src/reclaimer.rs
foyer-storage/src/reinsertion.rs
foyer-storage/src/store.rs

- support multiple admission or reinsertion policies
- loose flush exclusive lock

feat: support multiple admission or reinsertion policies, loose lock

---

.github/template/template.yml
.github/workflows/main.yml
.github/workflows/pull-request.yml
foyer-common/src/code.rs
foyer-intrusive/src/core/adapter.rs
foyer-storage/src/admission/all.rs
foyer-storage/src/admission/mod.rs
foyer-storage/src/admission/rated_random.rs
foyer-storage/src/store.rs

feat: introduce rated random admission policy

---

foyer-storage/src/store.rs

fix: recovery run flushers and reclaimers first

---

foyer-storage-bench/src/main.rs

fix: raise error in bench metrics instead of panic

---

foyer-common/src/code.rs
foyer-intrusive/src/collections/hashmap.rs
foyer-intrusive/src/collections/mod.rs
foyer-intrusive/src/core/adapter.rs
foyer-storage/src/flusher.rs
foyer-storage/src/region_manager.rs

feat: introduce intrusive hashmap

---

Cargo.toml
foyer-common/src/code.rs
foyer-intrusive/src/collections/hashmap.rs
foyer-intrusive/src/eviction/fifo.rs
foyer-intrusive/src/eviction/lfu.rs
foyer-intrusive/src/eviction/lru.rs
foyer-intrusive/src/eviction/mod.rs
foyer-memory/Cargo.toml
foyer-memory/src/lib.rs

feat: introduce basic memory cache framework

---

foyer-storage-bench/src/main.rs
foyer-storage/src/flusher.rs
foyer-storage/src/reclaimer.rs
foyer-storage/src/store.rs

feat: introduce flush & reclaim rate limit

---

foyer-intrusive/src/collections/dlist.rs
foyer-intrusive/src/collections/duplicated_hashmap.rs
foyer-intrusive/src/collections/mod.rs

feat: introduce intrusive duplicated hashmap

---

foyer-storage-bench/src/main.rs
foyer-storage/src/indices.rs
foyer-storage/src/metrics.rs
foyer-storage/src/store.rs

feat: add prometheus namespace config

---

foyer-storage-bench/src/main.rs
foyer-storage/src/error.rs
foyer-storage/src/event.rs
foyer-storage/src/indices.rs
foyer-storage/src/lib.rs
foyer-storage/src/reclaimer.rs
foyer-storage/src/store.rs

feat: introduce event listener

---

foyer-storage/src/admission/mod.rs
foyer-storage/src/admission/rated_random.rs
foyer-storage/src/metrics.rs
foyer-storage/src/store.rs

feat: introduce store writer

---

foyer-storage/src/store.rs

fix: writer weight calculate

---

foyer-storage-bench/src/utils.rs
foyer-storage/Cargo.toml
foyer-storage/src/admission/mod.rs
foyer-storage/src/admission/rated_random.rs
foyer-storage/src/device/fs.rs
foyer-storage/src/metrics.rs
foyer-storage/src/store.rs

feat: refactor admission policy interface, fix rated random with multiple policies

---

foyer-storage/src/store.rs

feat: add more insert interfaces

---

foyer-storage/Cargo.toml
foyer-storage/src/error.rs
foyer-storage/src/store.rs

refactor: insert with interface allow return fetch value error

---

foyer-storage/src/metrics.rs
foyer-storage/src/store.rs

fix: refactor future interface in insert with

---

foyer-storage/src/store.rs

fix: reverse condition of insert if not exists

---

foyer-storage/src/device/mod.rs

fix: remove mistake cfg attr

---

foyer-storage/src/region.rs

fix: make slice drop recoverable

---

Makefile

chore: add makefile for check and test

---

.github/pull_request_template.md
README.md

chore: add README and pr template

---

foyer-intrusive/src/eviction/fifo.rs
foyer-intrusive/src/eviction/mod.rs
foyer-intrusive/src/eviction/sfifo.rs
foyer-memory/src/lib.rs
foyer-storage/src/lib.rs
foyer-storage/src/region_manager.rs
foyer-storage/src/store.rs

Add and use simple fifo by default.

feat: add and use simple fifo by default

---

foyer-storage/src/store.rs

fix: weight check

---

.github/template/template.yml
.github/workflows/main.yml
.github/workflows/pull-request.yml
.gitignore

chore: update ci to fix codecov

---

foyer-common/src/code.rs
foyer-common/src/lib.rs

chore: ignore some code cov to make it more accurate

---

.github/dependabot.yml

chore: enable dependabot version update

---

.github/template/template.yml
.github/workflows/main.yml
.github/workflows/pull-request.yml

chore(ci): use cargo-binstall to install tools

---

Makefile
scripts/install-deps.sh

chore: update makefile deps

---

.github/template/template.yml
.github/workflows/main.yml
.github/workflows/pull-request.yml
foyer-storage/src/lib.rs
rust-toolchain

https://github.com/dtolnay/thiserror/pull/246
https://github.com/rust-lang/rust/pull/113464
@MrCroxx BTW, can I update risingwave's foyer dependency to latest now?

fix build on latest nightly

---

Cargo.toml
foyer-workspace-hack/Cargo.toml

chore: fix workspace

---

foyer-storage/src/store.rs

fix: fix insert duration

---

.github/template/template.yml
.github/workflows/main.yml
.github/workflows/pull-request.yml
foyer-storage/src/device/error.rs
foyer-storage/src/error.rs
rust-toolchain

chore: downgrade rust toolchain

---

foyer-intrusive/src/lib.rs
foyer-storage-bench/src/main.rs
foyer-storage/src/flusher.rs
foyer-storage/src/lib.rs
foyer-storage/src/metrics.rs
foyer-storage/src/reclaimer.rs
foyer-storage/src/store.rs

refactor: use rust-prometheus global registry

---

foyer-storage/src/flusher.rs
foyer-storage/src/metrics.rs
foyer-storage/src/reclaimer.rs
foyer-storage/src/region_manager.rs
foyer-storage/src/store.rs

chore: export inner op metrics

---

Makefile
foyer-storage-bench/Cargo.toml
foyer-storage-bench/src/main.rs
foyer-storage/src/region.rs
foyer-storage/src/region_manager.rs
foyer-storage/src/store.rs
foyer-workspace-hack/Cargo.toml
scripts/jaeger.sh

Introduce tracing framework with OpenTelemetry and Jaeger.
#36

feat: integrate tracing framework

---

foyer-storage/Cargo.toml
foyer-storage/src/device/fs.rs
foyer-storage/src/region.rs
foyer-storage/src/region_manager.rs
foyer-workspace-hack/Cargo.toml

feat: use sync lock in ErwLock instead of async lock

---

foyer-storage-bench/src/analyze.rs
foyer-storage-bench/src/main.rs
foyer-storage/src/metrics.rs
foyer-storage/src/region_manager.rs
scripts/jaeger.sh

1. Set tracing span collector batch config larger.
2. Add more tracing info.

chore: enhance tracing

---

foyer-storage/src/metrics.rs
foyer-storage/src/store.rs

chore: export metrics registry

---

.config/hakari.toml
.github/template/template.yml
.github/workflows/main.yml
.github/workflows/pull-request.yml
Makefile
foyer-intrusive/src/lib.rs
foyer-storage-bench/src/utils.rs
foyer-storage/src/device/fs.rs
foyer-storage/src/store.rs
foyer-workspace-hack/Cargo.toml
rust-toolchain

chore: bump toolchain

---

foyer-storage/src/flusher.rs
foyer-storage/src/metrics.rs
foyer-storage/src/reclaimer.rs
foyer-storage/src/store.rs

chore: use uint gauge instead

---

.github/pull_request_template.md

chore: simplify pr template

---

.github/template/template.yml
.github/workflows/main.yml
.github/workflows/pull-request.yml
Makefile
foyer-common/src/lib.rs
foyer-common/src/rated_random.rs
foyer-common/src/rated_ticket.rs
foyer-storage-bench/src/main.rs
foyer-storage/src/admission/mod.rs
foyer-storage/src/admission/rated_ticket.rs
foyer-storage/src/reinsertion/mod.rs
foyer-storage/src/reinsertion/rated_random.rs
foyer-storage/src/reinsertion/rated_ticket.rs

As titled. Compared to rated random policy, rated ticket policy drop requests if there is no quota left.

feat: introduce rated ticket admission & reinsertion policy

---

foyer-storage-bench/src/analyze.rs
foyer-storage-bench/src/main.rs

fix: fix foyer storage bench tool analysis

---

foyer-storage/src/judge.rs
foyer-storage/src/store.rs

feat: introduce force insert interface

---

foyer-storage/src/region.rs
foyer-storage/src/store.rs

fix: fix recovery load unwrap

---

foyer-common/Cargo.toml
foyer-common/src/erwlock.rs
foyer-common/src/lib.rs
foyer-storage/src/region.rs
foyer-workspace-hack/Cargo.toml

refactor: refine erwlock

---

Makefile
foyer-common/Cargo.toml
foyer-intrusive/Cargo.toml
foyer-memory/Cargo.toml
foyer-storage-bench/Cargo.toml
foyer-storage/Cargo.toml
foyer/Cargo.toml

chore: add udeps check

---

foyer-storage/src/generic.rs

chore: remove unused

---

foyer-storage/src/lazy.rs

chore: fix lazy store clone

---

codecov.yml

chore: add codecov config

---

foyer-common/src/lib.rs
foyer-common/src/runtime.rs
foyer-storage-bench/src/main.rs
foyer-storage/src/generic.rs
foyer-storage/src/lazy.rs
foyer-storage/src/lib.rs
foyer-storage/src/reclaimer.rs
foyer-storage/src/runtime.rs
foyer-storage/src/storage.rs
foyer-storage/src/store.rs

Changes:
- Refactor `GenericStore` to hold `Arc<GenericStoreInner>`.
- Refactor `GenericWriter` to make its lifetime `'static`.
- Refactor `LazyStore` to make it receive generic `Storage` type.
- Introduce `RuntimeStore` which receives generic `Storage` type and poll async task in separate runtime.

feat: introduce runtime store

---

foyer-storage/src/device/fs.rs
foyer-storage/src/device/mod.rs
foyer-storage/src/generic.rs
foyer-storage/src/lazy.rs
foyer-storage/src/lib.rs
foyer-storage/src/runtime.rs
foyer-storage/src/storage.rs
foyer-storage/src/store.rs
foyer-storage/src/test_utils.rs
foyer-storage/tests/storage_test.rs

test: introduce basic generic storage test

---

foyer-storage/src/lazy.rs
foyer-storage/src/runtime.rs
foyer-storage/tests/storage_test.rs

chore: export LazyStore and RuntimeStore to simplify code

---

foyer-storage/src/generic.rs
foyer-storage/src/lazy.rs
foyer-storage/src/runtime.rs
foyer-storage/src/storage.rs
foyer-storage/src/store.rs
foyer-storage/tests/storage_test.rs

chore: export RuntimeLazyStore and fix fn ready

---

foyer-storage/src/lazy.rs
foyer-storage/src/store.rs

refactor: move NoneStore into Store

---

foyer-storage/src/storage.rs

feat: introduce async storage ext

---

foyer-storage/src/generic.rs
foyer-storage/src/lazy.rs
foyer-storage/src/runtime.rs
foyer-storage/src/storage.rs
foyer-storage/src/store.rs

feat: expose writer key & weight

---

foyer-storage/src/region.rs

chore: remove unused code

---

foyer-storage/src/region.rs

chore: clean code

---

foyer-storage/src/region_manager.rs

chore: fix acquire clean buffer metrics

---

foyer-storage-bench/src/main.rs
foyer-storage/src/generic.rs
foyer-storage/src/lazy.rs
foyer-storage/src/runtime.rs
foyer-storage/src/storage.rs
foyer-storage/src/store.rs

refactor: move force to storage writer trait

---

foyer-storage/src/device/fs.rs
foyer-storage/src/device/mod.rs
foyer-storage/src/flusher.rs
foyer-storage/src/reclaimer.rs
foyer-storage/src/region.rs

refactor: refine devcie interface with buffer

---

foyer-storage/src/device/fs.rs
foyer-storage/src/device/mod.rs
foyer-storage/src/flusher.rs

refactor: remove unnecessary unsafe silce usage

---

foyer-common/src/code.rs

refactor: code api receives Buf and BufMut to support non-continuous buf

---

foyer-common/src/code.rs

Revert "refactor: code api receives Buf and BufMut to support non-continuous buf"

---

foyer-common/Cargo.toml
foyer-common/src/continuum.rs
foyer-common/src/lib.rs

feat: introduce concurrent Continuum tracker

---

.github/template/template.yml
.github/workflows/main.yml
.github/workflows/pull-request.yml
Makefile
foyer-common/src/continuum.rs
foyer-storage/src/lib.rs
foyer-storage/src/ring.rs

feat: introduce ring buffer

---

.github/template/template.yml
.github/workflows/main.yml
.github/workflows/pull-request.yml
foyer-common/src/code.rs
foyer-common/src/continuum.rs
foyer-common/src/lib.rs
foyer-intrusive/src/lib.rs
foyer-storage-bench/src/main.rs
foyer-storage/src/lib.rs
foyer-storage/src/ring.rs
foyer-storage/src/store.rs
rust-toolchain

chore: bump toolchain to 2023-10-21

---

foyer-storage/Cargo.toml
foyer-storage/src/generic.rs
foyer-workspace-hack/Cargo.toml

chore: use semaphore to control recovery concurrency

---

Makefile
foyer-storage/src/catalog.rs
foyer-storage/src/flusher_v2.rs
foyer-storage/src/generic.rs
foyer-storage/src/metrics.rs
foyer-storage/src/ring.rs

chore: refine metrics for new write model

---

foyer-storage/src/flusher_v2.rs
foyer-storage/src/generic.rs
foyer-storage/src/metrics.rs
foyer-storage/src/ring.rs

feat: advance continuum when submit

---

foyer-common/src/code.rs
foyer-storage-bench/src/main.rs
foyer-storage/Cargo.toml
foyer-storage/src/buffer.rs
foyer-storage/src/compress.rs
foyer-storage/src/flusher.rs
foyer-storage/src/generic.rs
foyer-storage/src/lazy.rs
foyer-storage/src/lib.rs
foyer-storage/tests/storage_test.rs
foyer-workspace-hack/Cargo.toml

feat: support zstd compression

---

foyer-storage/src/buffer.rs
foyer-storage/src/compress.rs
foyer-storage/src/flusher.rs
foyer-storage/src/generic.rs
foyer-storage/src/region.rs

chore: clear compression code logic

---

foyer-storage-bench/src/main.rs
foyer-storage/Cargo.toml
foyer-storage/src/buffer.rs
foyer-storage/src/compress.rs
foyer-storage/src/generic.rs
foyer-storage/tests/storage_test.rs

feat: add lz4 support

---

foyer-storage-bench/src/main.rs
foyer-storage/src/compress.rs
foyer-storage/src/generic.rs

chore: tiny refactor about compression

---

foyer-storage-bench/etc/sample.txt
foyer-storage-bench/src/analyze.rs
foyer-storage-bench/src/main.rs
foyer-storage-bench/src/text.rs

feat: bench tool gen data based on real text

---

.gitignore
foyer-storage-bench/src/main.rs
foyer-storage/src/buffer.rs
foyer-storage/src/flusher.rs
foyer-storage/src/generic.rs
foyer-storage/src/lazy.rs
foyer-storage/src/runtime.rs
foyer-storage/src/storage.rs
foyer-storage/src/store.rs

As titled. Now each entry can use different compression algorithm with writer api.

feat: support per entry compression algorithm

---

foyer-common/Cargo.toml
foyer-common/src/code.rs
foyer-storage/src/buffer.rs
foyer-storage/src/generic.rs

Coding error is always a logical error, which will be reported to the caller, except when recovering.

refactor: support coding error

---

foyer-storage-bench/Cargo.toml

chore: bench tool use madsim tokio

---

foyer-storage/src/admission/mod.rs
foyer-storage/src/admission/rated_random.rs
foyer-storage/src/admission/rated_ticket.rs
foyer-storage/src/generic.rs
foyer-storage/src/reclaimer.rs
foyer-storage/src/reinsertion/exist.rs
foyer-storage/src/reinsertion/mod.rs
foyer-storage/src/reinsertion/rated_random.rs
foyer-storage/src/reinsertion/rated_ticket.rs
foyer-storage/src/test_utils.rs

refactor: refactor admission and reinsertion policy with context

---

foyer-storage-bench/Cargo.toml
foyer-storage-bench/src/export.rs
foyer-workspace-hack/Cargo.toml

chore: upgrade hyper to 1.0

---

foyer-storage/src/buffer.rs
foyer-storage/src/generic.rs
foyer-storage/src/region.rs

feat: add format version in region header

---

foyer-common/src/code.rs
foyer-common/src/lib.rs
foyer-storage-bench/src/main.rs
foyer-storage/src/admission/mod.rs
foyer-storage/src/admission/rated_ticket.rs
foyer-storage/src/buffer.rs
foyer-storage/src/catalog.rs
foyer-storage/src/error.rs
foyer-storage/src/flusher.rs
foyer-storage/src/generic.rs
foyer-storage/src/lib.rs
foyer-storage/src/reinsertion/exist.rs
foyer-storage/src/reinsertion/mod.rs
foyer-storage/src/reinsertion/rated_ticket.rs

As titled.
No performance regression after the refactor.
#216 #226

refactor: introduce inflight item into catalog, refactor coding

---

foyer-common/src/code.rs

refactor: simplify cursor interface

---

foyer-common/Cargo.toml
foyer-intrusive/Cargo.toml
foyer-storage-bench/Cargo.toml
foyer-storage/Cargo.toml
foyer/Cargo.toml

chore: bump version to 0.3

---

foyer-storage/Cargo.toml

chore: bump foyer-storage to 0.2.1

---

foyer-storage/src/storage.rs

As titled.
This PR will be used to impl write handle to reduce cache miss during insertion.
- Memory cache insert a value synchronously and put a write handle of the inserted key, the operation doesn't need async code.
- When callback is called, the write handle should be removed sync/async.

feat: add insert if not exist with callback interface, add uts

---

foyer-storage/src/storage.rs

As titled. Much like #239 
#239

feat: add insert_async_with_callback

---

foyer-storage/src/storage.rs

Reverts MrCroxx/foyer#241
The check condition is not correctly set. One failed but merged.

Revert "feat: add insert_async_with_callback"

---

CHANGELOG.md
foyer-storage/Cargo.toml

chore: bump foyer-storage to 0.2.2

---

foyer-storage-bench/src/main.rs

fix: fix another factor that make bench miss ratio not accurate

---

CHANGELOG.md
foyer-storage-bench/Cargo.toml
foyer-storage/Cargo.toml
foyer-workspace-hack/Cargo.toml
foyer/Cargo.toml

See [CHANGELOG.md](https://github.com/MrCroxx/foyer/blob/9df0fdb18798214ca7d874c74a862fc09216b441/CHANGELOG.md)

chore: bump foyer version

---

foyer-storage/src/generic.rs

fix: fix duplicated insert dropped metrics

---

foyer-storage-bench/src/main.rs

chore: remove unused ut

---

CHANGELOG.md
foyer-common/Cargo.toml
foyer-intrusive/Cargo.toml
foyer-memory/Cargo.toml
foyer-storage-bench/Cargo.toml
foyer-storage/Cargo.toml
foyer-workspace-hack/Cargo.toml
foyer/Cargo.toml

chore: bump foyer 0.5.0

---

Cargo.toml
codecov.yml
foyer-experimental-bench/Cargo.toml
foyer-experimental-bench/benches/wal-bench.rs
foyer-experimental-bench/etc/sample.txt
foyer-experimental-bench/src/analyze.rs
foyer-experimental-bench/src/export.rs
foyer-experimental-bench/src/lib.rs
foyer-experimental-bench/src/rate.rs
foyer-experimental-bench/src/text.rs
foyer-experimental-bench/src/utils.rs
foyer-experimental/Cargo.toml
foyer-experimental/src/metrics.rs
foyer-experimental/src/wal.rs
foyer-storage/src/reclaimer.rs

refactor: refine foyer-experimental-bench structure

---

foyer-intrusive/src/collections/dlist.rs
foyer-intrusive/src/collections/duplicated_hashmap.rs
foyer-intrusive/src/collections/hashmap.rs
foyer-intrusive/src/core/adapter.rs
foyer-intrusive/src/eviction/fifo.rs
foyer-intrusive/src/eviction/lfu.rs
foyer-intrusive/src/eviction/lru.rs
foyer-intrusive/src/eviction/sfifo.rs
foyer-memory/src/eviction/fifo.rs
foyer-workspace-hack/Cargo.toml

chore: fix typo, rename DList to Dlst to make it more Rustful

---

foyer-intrusive/src/collections/dlist.rs
foyer-intrusive/src/collections/duplicated_hashmap.rs
foyer-intrusive/src/collections/hashmap.rs
foyer-intrusive/src/core/adapter.rs
foyer-intrusive/src/eviction/fifo.rs
foyer-intrusive/src/eviction/lfu.rs
foyer-intrusive/src/eviction/lru.rs
foyer-intrusive/src/eviction/sfifo.rs

refactor: use NonNull instead of raw pointer in foyer-intrusive

---

foyer-intrusive/src/collections/dlist.rs
foyer-intrusive/src/collections/duplicated_hashmap.rs
foyer-intrusive/src/collections/hashmap.rs
foyer-intrusive/src/core/pointer.rs
foyer-intrusive/src/eviction/fifo.rs
foyer-intrusive/src/eviction/lfu.rs
foyer-intrusive/src/eviction/lru.rs
foyer-intrusive/src/eviction/sfifo.rs

chore: rename fn name for Pointer

---

rustfmt.toml

chore: add comments max width fmt check

---

.github/pull_request_template.md

chore: update the PR template

---

foyer-memory/src/cache.rs
foyer-memory/src/event.rs
foyer-memory/src/handle.rs
foyer-memory/src/lib.rs
foyer-memory/src/listener.rs

refactor: use generic type instead of associated type for listener

---

foyer-memory/src/cache.rs
foyer-memory/src/indexer.rs
foyer-memory/src/lib.rs
foyer-memory/src/prelude.rs

refactor: use prelude mod to restrict visibility 

---

Cargo.toml
foyer-experimental-bench/Cargo.toml
foyer-storage-bench/Cargo.toml
foyer-storage/Cargo.toml

As title.
close #264 #265 #266 #267 #268

chore: upgrade  dependencies, fix target auto detect

---

foyer-memory/src/cache.rs
foyer-memory/src/context.rs
foyer-memory/src/eviction/fifo.rs
foyer-memory/src/eviction/lfu.rs
foyer-memory/src/eviction/lru.rs
foyer-memory/src/generic.rs
foyer-memory/src/lib.rs
foyer-memory/src/prelude.rs

refactor: unify in-memory cache to simplify usage

---

foyer-memory/src/cache.rs

test: add test for unified cache

---

CHANGELOG.md
foyer-common/Cargo.toml
foyer-experimental-bench/Cargo.toml
foyer-experimental/Cargo.toml
foyer-intrusive/Cargo.toml
foyer-memory/Cargo.toml
foyer-storage-bench/Cargo.toml
foyer-storage/Cargo.toml
foyer-workspace-hack/Cargo.toml
foyer/Cargo.toml

chore: bump version and release foyer 0.6.0

---

foyer-experimental-bench/src/lib.rs
foyer-storage-bench/src/main.rs

fix: fix build with trace future

---

CHANGELOG.md
foyer-experimental-bench/Cargo.toml
foyer-storage-bench/Cargo.toml

chore: bump bench tools version

---

CHANGELOG.md
foyer-memory/Cargo.toml

chore: bump foyer-memory to 0.1.1

---

foyer-memory/src/prelude.rs

refactor: export DefaultCacheEventListener

---

foyer-memory/Cargo.toml

chore: bump foyer-memory version

---

CHANGELOG.md
foyer-intrusive/Cargo.toml
foyer-memory/Cargo.toml

chore: bump foyer-intrusive to 0.3.1, foyer-memory to 0.1.3

---

CHANGELOG.md
foyer-storage/Cargo.toml

chore: bump foyer-storage to 0.5.1

---

CHANGELOG.md
foyer-memory/Cargo.toml

chore: bump foyer-memory to 0.1.4

---

foyer-common/Cargo.toml
foyer-common/src/bits.rs
foyer-common/src/code.rs
foyer-common/src/lib.rs
foyer-common/src/range.rs
foyer-experimental/Cargo.toml
foyer-experimental/src/error.rs
foyer-experimental/src/lib.rs
foyer-experimental/src/metrics.rs
foyer-experimental/src/wal.rs
foyer-intrusive/src/eviction/mod.rs
foyer-intrusive/src/lib.rs
foyer-storage/Cargo.toml
foyer-storage/src/buffer.rs
foyer-storage/src/device/allocator.rs
foyer-storage/src/device/mod.rs
foyer-storage/src/flusher.rs
foyer-storage/src/lib.rs
foyer-storage/src/metrics.rs
foyer-storage/src/storage.rs
foyer/src/lib.rs

As title. TODOs are left as reminders after the features are stable.
#310

refactor: remove usage of unstable features

---

.github/template/template.yml
.github/workflows/main.yml
.github/workflows/pull-request.yml
foyer-experimental-bench/src/utils.rs
foyer-storage-bench/src/utils.rs
foyer-storage/src/device/fs.rs

test: run CI on both linux and macos

---

.config/hakari.toml
Cargo.toml
README.md
examples/Cargo.toml
examples/memory.rs
foyer-common/Cargo.toml
foyer-experimental-bench/Cargo.toml
foyer-experimental/Cargo.toml
foyer-intrusive/Cargo.toml
foyer-memory/Cargo.toml
foyer-storage-bench/Cargo.toml
foyer-storage/Cargo.toml
foyer-workspace-hack/Cargo.toml
foyer/Cargo.toml

doc: update README and add a simple example

---

README.md
foyer/Cargo.toml

chore: add msrv for foyer, update bager in readme

---

foyer-experimental/src/wal.rs

fix: do not truncate when open wal

---

foyer-memory/Cargo.toml
foyer-memory/benches/bench_dynamic_dispatch.rs

perf: add dynamic dispatch bench

---

.github/template/template.yml
.github/workflows/main.yml
.github/workflows/pull-request.yml

test: upload binaries when asan/lsan test fails

---

foyer-memory/src/cache.rs
foyer-memory/src/generic.rs

feat: add `pop()` and `pop_corase()` interface for in-memory cache

---

examples/memory.rs
foyer-memory/benches/bench_hit_ratio.rs
foyer-memory/src/cache.rs
foyer-memory/src/eviction/fifo.rs
foyer-memory/src/eviction/lfu.rs
foyer-memory/src/eviction/lru.rs
foyer-memory/src/eviction/mod.rs
foyer-memory/src/eviction/s3fifo.rs
foyer-memory/src/generic.rs
foyer-memory/src/prelude.rs
foyer-storage-bench/Cargo.toml
foyer-storage-bench/src/main.rs
foyer-storage/Cargo.toml
foyer-storage/src/flusher.rs
foyer-storage/src/generic.rs
foyer-storage/src/lazy.rs
foyer-storage/src/reclaimer.rs
foyer-storage/src/region_manager.rs
foyer-storage/src/storage.rs
foyer-storage/src/store.rs
foyer-storage/tests/storage_test.rs

Use `foyer-memory` to refactor `foyer-storage`.

refactor: use in-memory cache to refactor disk cache

---

.github/template/template.yml
.github/workflows/main.yml
.github/workflows/pull-request.yml

chore: enable rust backtrace for nextest

---

.github/template/template.yml
.github/workflows/main.yml
.github/workflows/pull-request.yml

chore: disable fall-fast for rust test ci

---

foyer-storage-bench/src/main.rs
foyer-storage/src/lazy.rs
foyer-storage/src/lib.rs
foyer-storage/src/none.rs
foyer-storage/src/runtime.rs
foyer-storage/src/store.rs
foyer-storage/tests/storage_test.rs

feat: introduce unified store, store write, store config

---

foyer-experimental-bench/src/export.rs
foyer-storage-bench/src/export.rs
foyer-storage-bench/src/main.rs
foyer-storage/src/judge.rs
foyer-storage/src/prelude.rs
foyer-storage/src/region.rs
foyer-storage/tests/storage_test.rs

refactor: use prelude to limit foyer-storage access

---

foyer-common/src/code.rs
foyer-storage/src/catalog.rs
foyer-storage/src/generic.rs
foyer-storage/src/lazy.rs
foyer-storage/src/none.rs
foyer-storage/src/runtime.rs
foyer-storage/src/storage.rs
foyer-storage/src/store.rs

Make `foyer-storage` support query with broader types.
close #362

refactor: loose query key bound for foyer-storage

---

foyer-storage/src/buffer.rs

fix: fix build on apple silicon

---

examples/memory.rs
foyer-memory/benches/bench_hit_ratio.rs
foyer-memory/src/cache.rs
foyer-memory/src/generic.rs
foyer-storage/src/region_manager.rs

feat: introduce weighter for in-memory cache

---

foyer-storage/src/device/mod.rs
foyer-storage/src/generic.rs
foyer-storage/src/region.rs

perf: load each entry with at most one request

---

foyer-storage-bench/src/analyze.rs
foyer-storage-bench/src/main.rs
foyer-storage/src/catalog.rs

As title.
#385 (may be not related)

test: add warm up for foyer-storage-bench, use ahash to hash catalog

---

foyer-common/src/code.rs
foyer-storage/src/admission/mod.rs
foyer-storage/src/admission/rated_ticket.rs
foyer-storage/src/buffer.rs
foyer-storage/src/device/mod.rs
foyer-storage/src/flusher.rs
foyer-storage/src/generic.rs
foyer-storage/src/lazy.rs
foyer-storage/src/reclaimer.rs
foyer-storage/src/region_manager.rs
foyer-storage/src/reinsertion/mod.rs
foyer-storage/src/runtime.rs
foyer-storage/src/storage.rs
foyer-storage/src/store.rs

chore: remove debug bound for storage key value

---

examples/hybrid.rs

chore: fix example

---

foyer-common/src/code.rs
foyer/src/hybrid.rs

refacor: refactor clone bound

---

foyer-common/src/arc_key_hash_map.rs
foyer-memory/src/cache.rs
foyer-memory/src/generic.rs
foyer-memory/src/indexer.rs
foyer-memory/src/listener.rs
foyer/src/hybrid.rs

refactor: use Arc<K> Arc<V> for in-memory cache handle

---

foyer-storage/src/catalog.rs
foyer-storage/src/flusher.rs
foyer-storage/src/generic.rs
foyer-storage/src/lazy.rs
foyer-storage/src/none.rs
foyer-storage/src/runtime.rs
foyer-storage/src/storage.rs
foyer-storage/src/store.rs
foyer/src/hybrid.rs

Remove the last Clone bound!
close #394

refactor: remove clone bound from entry()

---

CHANGELOG.md
foyer-common/Cargo.toml
foyer-experimental-bench/Cargo.toml
foyer-experimental/Cargo.toml
foyer-intrusive/Cargo.toml
foyer-memory/Cargo.toml
foyer-storage-bench/Cargo.toml
foyer-storage/Cargo.toml
foyer-workspace-hack/Cargo.toml
foyer/Cargo.toml

chore: release foyer v0.8

---

README.md
examples/hybrid_full.rs
foyer-storage/Cargo.toml
foyer-storage/src/buffer.rs
foyer-storage/src/device/fs.rs
foyer-storage/src/device/mod.rs
foyer-storage/src/flusher.rs
foyer-storage/src/generic.rs
foyer-storage/src/lazy.rs
foyer-storage/src/storage.rs
foyer-storage/src/store.rs
foyer-storage/tests/storage_test.rs
foyer-workspace-hack/Cargo.toml
foyer/src/hybrid.rs

As title.
fix #320 
close #370

feat: add config to control flush for io

---

CHANGELOG.md
README.md
foyer-common/Cargo.toml
foyer-intrusive/Cargo.toml
foyer-memory/Cargo.toml
foyer-storage-bench/Cargo.toml
foyer-storage/Cargo.toml
foyer-workspace-hack/Cargo.toml
foyer/Cargo.toml

chore: release foyer v0.8.1

---

.config/hakari.toml
foyer-storage/Cargo.toml
foyer-storage/src/lib.rs
foyer-workspace-hack/Cargo.toml
foyer/Cargo.toml
foyer/src/lib.rs

fix: fix build with night feature

---

CHANGELOG.md
README.md
foyer-common/Cargo.toml
foyer-intrusive/Cargo.toml
foyer-memory/Cargo.toml
foyer-storage-bench/Cargo.toml
foyer-storage/Cargo.toml
foyer-workspace-hack/Cargo.toml
foyer/Cargo.toml

chore: relase foyer v0.8.2

---

foyer/src/lib.rs
foyer/src/prelude.rs

refactor: expose code traits

---

CHANGELOG.md
foyer/Cargo.toml

chore: release foyer v0.8.3

---

foyer/src/prelude.rs

refactor: expose hybrid cache entry

---

CHANGELOG.md
foyer/Cargo.toml

chore: relase foyer v0.8.4

---

foyer/src/hybrid.rs

refactor: add default random state for hybrid entry

---

foyer/src/prelude.rs

refactor: expose entry state

---

foyer/src/hybrid.rs

refactor: loose entry args trait bound

---

foyer/src/prelude.rs

refactor: expose storage writer

---

foyer/src/prelude.rs

refactor: export metrics related components

---

foyer/src/prelude.rs

refactor: expose RangeBoundsExt, BufExt and BufMutExt

---

CHANGELOG.md
foyer/Cargo.toml

chore: release foyer v0.8.5

---

.github/template/template.yml
.github/workflows/main.yml
.github/workflows/pull-request.yml
Makefile
foyer-experimental/Cargo.toml
foyer-experimental/src/wal.rs

chore: upgrade ci actions

---

.github/template/template.yml
.github/workflows/main.yml
.github/workflows/pull-request.yml
Makefile
foyer-common/Cargo.toml
foyer-experimental-bench/Cargo.toml
foyer-experimental/Cargo.toml
foyer-intrusive/Cargo.toml
foyer-memory/Cargo.toml
foyer-storage-bench/Cargo.toml
foyer-storage/Cargo.toml
foyer/Cargo.toml

chore: remove unused dependencies, add udeps ci

---

CHANGELOG.md
foyer-common/Cargo.toml
foyer-intrusive/Cargo.toml
foyer-memory/Cargo.toml
foyer-storage-bench/Cargo.toml
foyer-storage/Cargo.toml
foyer/Cargo.toml

chore: release foyer v0.8.6

---

foyer-storage/src/device/fs.rs

fix: fix `freespace()` on non-exist path

---

CHANGELOG.md
foyer-storage/Cargo.toml

chore: release foyer-storage v0.7.4

---

CHANGELOG.md
foyer-memory/Cargo.toml

chore: release foyer-memory v0.3.4

---

foyer/src/hybrid.rs

refactor: impl Clone for hybrid cache

---

CHANGELOG.md
foyer/Cargo.toml

chore: release foyer 0.8.7

---

Cargo.toml
foyer-common/Cargo.toml
foyer-memory/Cargo.toml
foyer-memory/src/cache.rs
foyer-memory/src/eviction/fifo.rs
foyer-memory/src/eviction/lfu.rs
foyer-memory/src/eviction/lru.rs
foyer-memory/src/eviction/mod.rs
foyer-memory/src/eviction/s3fifo.rs
foyer-storage-bench/Cargo.toml
foyer-storage/Cargo.toml
foyer/src/hybrid.rs

As title.
close #438 
close #439 
close #440

feat: impl Default, serde for eviction configs, impl debug for hybrid

---

CHANGELOG.md
foyer-memory/Cargo.toml
foyer-storage-bench/Cargo.toml
foyer-storage/Cargo.toml
foyer/Cargo.toml

chore: release foyer v0.8.8

---

foyer-common/Cargo.toml
foyer-common/src/range.rs

refactor: restore bound map with cfg

---

CHANGELOG.md
foyer-common/Cargo.toml
foyer-memory/Cargo.toml
foyer-storage-bench/Cargo.toml
foyer-storage/Cargo.toml
foyer/Cargo.toml

chore: release foyer v0.8.9

---

foyer-storage/Cargo.toml
foyer-storage/src/device/fs.rs

chore: remove some uncessary deps

---

foyer-storage/src/buffer.rs
foyer-storage/src/device/allocator.rs
foyer-storage/src/error.rs
foyer-storage/src/flusher.rs
foyer-storage/src/generic.rs
foyer-storage/src/lib.rs
foyer-storage/src/serde.rs

refactor: extract key value serde code to serde mod

---

foyer-common/src/slab/mod.rs
foyer-common/src/slab/slab_linked_list/mod.rs

fix: fix stable 1.78 clippy check

---

foyer-storage/src/large/device/direct_file.rs
foyer-storage/src/large/device/mod.rs

feat: introduce direct file device

---

foyer-storage/Cargo.toml
foyer-storage/src/large/device/direct_file.rs
foyer-storage/src/large/device/direct_fs.rs
foyer-storage/src/large/device/mod.rs
foyer-storage/src/large/generic.rs
foyer-storage/src/large/mod.rs
foyer-storage/src/large/tombstone.rs

feat: introduce tombstone log on direct fs device

---

foyer-storage/src/large/flusher.rs
foyer-storage/src/large/generic.rs
foyer-storage/src/large/indexer.rs
foyer-storage/src/large/reclaimer.rs
foyer-storage/src/large/recover.rs
foyer-storage/src/large/region.rs
foyer-storage/src/large/storage.rs
foyer-storage/src/large/tombstone.rs

As title.
#447 #449
close #461

feat: write tombstone log when delete entry if enabled

---

foyer-common/src/judge.rs
foyer-memory/src/generic.rs
foyer-storage/src/large/admission.rs
foyer-storage/src/large/generic.rs
foyer-storage/src/large/test_utils.rs

refactor: admission picker only receives key

---

foyer-storage/src/large/generic.rs
foyer-storage/src/large/reclaimer.rs

fix: flush region cleaner if flush is enabled

---

foyer-storage/src/large/admission.rs
foyer-storage/src/large/generic.rs
foyer-storage/src/large/mod.rs
foyer-storage/src/large/none.rs
foyer-storage/src/large/recover.rs
foyer-storage/src/large/reinsertion.rs
foyer-storage/src/large/runtime.rs
foyer-storage/src/large/storage.rs
foyer-storage/src/large/store.rs

feat: introduce unified store and builder for the new engine

---

foyer-storage/src/serde.rs

fix: fix coredump

---

foyer-memory/Cargo.toml
foyer-memory/src/generic.rs

fix: fix entry() hang when None is returned

---

foyer-storage/src/large/flusher.rs

fix: fix entry addr calculation when concurrent write

---

README.md
examples/hybrid_full.rs
foyer-memory/src/cache.rs
foyer-memory/src/generic.rs
foyer-memory/src/prelude.rs
foyer-storage/src/large/flusher.rs
foyer-storage/src/large/recover.rs
foyer/src/hybrid/cache.rs
foyer/src/prelude.rs

refactor: rename interface "entry" to "fetch"

---

foyer-storage/src/large/flusher.rs
foyer-storage/src/large/reclaimer.rs
foyer-storage/src/large/recover.rs
foyer-storage/src/large/scanner.rs
foyer-storage/src/region.rs

refactor: restrict region device ops, update region access stats

---

foyer-common/src/code.rs
foyer-memory/src/cache.rs
foyer-memory/src/generic.rs
foyer-storage/src/large/flusher.rs
foyer-storage/src/large/generic.rs
foyer-storage/src/large/reclaimer.rs
foyer-storage/src/large/recover.rs
foyer-storage/src/storage.rs
foyer-storage/src/store/mod.rs
foyer-storage/src/store/noop.rs
foyer/src/hybrid/builder.rs
foyer/src/hybrid/cache.rs

refactor: make trait alias HashBuilder

---

foyer-storage/src/device/mod.rs
foyer-storage/src/device/monitor.rs
foyer-storage/src/large/flusher.rs
foyer-storage/src/large/generic.rs
foyer-storage/src/large/recover.rs
foyer-storage/src/region.rs
foyer-storage/src/storage.rs
foyer-storage/src/store/mod.rs
foyer-storage/src/store/noop.rs
foyer-storage/src/store/runtime.rs
foyer-storage/src/tombstone.rs

feat: introduce monitored device and device stat

---

foyer-storage/Cargo.toml
foyer-storage/src/large/indexer.rs
foyer-storage/src/large/scanner.rs
foyer-storage/src/lib.rs
foyer-storage/src/metrics.rs
foyer-storage/src/region.rs

refactor: restrict foyer-storage visibility

---

foyer-common/src/async_batch_pipeline.rs
foyer-storage/src/large/flusher.rs

As title.
Fixes:
1. Fix async batch pipeline doesn't accumulate while there is a pending background pipeline task.
2. Fix write batch split condition,
#447

fix: fix async batch pipeline concurrent ops

---

foyer-bench/src/main.rs

fix: fix foyer bench tool read range calculation

---

foyer-memory/src/cache.rs
foyer-memory/src/generic.rs
foyer-storage/src/large/generic.rs
foyer-storage/src/storage.rs
foyer-storage/src/store/mod.rs
foyer-storage/src/store/noop.rs
foyer-storage/src/store/runtime.rs
foyer-storage/tests/storage_test.rs
foyer/Cargo.toml
foyer/src/hybrid/cache.rs

feat: support insert storage with fetch

---

foyer-storage/src/compress.rs
foyer-storage/src/device/direct_file.rs
foyer-storage/src/device/direct_fs.rs
foyer-storage/src/device/mod.rs
foyer-storage/src/device/monitor.rs
foyer-storage/src/large/recover.rs
foyer-storage/src/lib.rs
foyer-storage/src/picker/mod.rs
foyer-storage/src/picker/utils.rs
foyer-storage/src/statistics.rs
foyer-storage/src/storage.rs
foyer-storage/src/store/mod.rs
foyer-storage/src/store/runtime.rs
foyer-storage/src/test_utils.rs
foyer-storage/src/tombstone.rs
foyer-storage/tests/storage_test.rs

doc: fullfill documentations for the foyer-storage crate

---

foyer-common/src/async_batch_pipeline.rs
foyer-common/src/asyncify.rs
foyer-common/src/bits.rs
foyer-common/src/buf.rs
foyer-common/src/code.rs
foyer-common/src/countdown.rs
foyer-common/src/fs.rs
foyer-common/src/lib.rs
foyer-common/src/metrics.rs
foyer-common/src/object_pool.rs
foyer-common/src/range.rs
foyer-common/src/rate.rs
foyer-common/src/rated_ticket.rs
foyer/src/hybrid/cache.rs

doc: fullfill documentations for crate foyer-common

---

foyer-storage/src/large/reclaimer.rs

fix: fix build with nightly feature

---

Cargo.toml
foyer-bench/Cargo.toml
foyer-common/Cargo.toml
foyer-intrusive/Cargo.toml
foyer-intrusive/src/dlist.rs
foyer-memory/Cargo.toml
foyer-storage/Cargo.toml
foyer-util/Cargo.toml

chore: update deps

---

foyer/src/hybrid/cache.rs
foyer/src/hybrid/mod.rs
foyer/src/hybrid/writer.rs
foyer/src/prelude.rs

As title. The writers provide more flexible APIs.
#447

feat: introduce hybrid cache writers

---

foyer-memory/Cargo.toml
foyer-memory/src/cache.rs
foyer-memory/src/generic.rs
foyer/src/hybrid/cache.rs

fix: fix panickes when obtain not exist

---

foyer-bench/Cargo.toml

As title.
https://github.com/tokio-rs/tracing-opentelemetry/issues/141

chore: downgrade opentelemty to fix build with trace feature

---

scripts/install-deps.sh

chore: use cargo install to install deps instead of cargo-binstall

---

foyer-bench/Cargo.toml

chore: udeps

---

foyer/src/hybrid/cache.rs

fix: add hybrid cache metrics for fetch

---

CHANGELOG.md
README.md
foyer-bench/Cargo.toml
foyer-common/Cargo.toml
foyer-intrusive/Cargo.toml
foyer-memory/Cargo.toml
foyer-storage/Cargo.toml
foyer/Cargo.toml

🎉 Release foyer v0.9 .
close #512

chore: release foyer v0.9

---

foyer-storage/src/large/generic.rs
foyer/src/hybrid/builder.rs

fix: fix memory cache metrics name building

---

foyer-memory/src/eviction/lru.rs
foyer-memory/src/generic.rs

test: refine in-memory fuzzy test

---

foyer-memory/src/generic.rs

test: add some asserts and comments

---

foyer-bench/src/main.rs

As title.
Support `--eviction lfu` and other algorithms with default configurations.

bench: support set eviction algorithm for foyer bench

---

foyer-common/src/assert.rs
foyer-intrusive/src/dlist.rs
foyer-memory/src/eviction/lfu.rs
foyer-memory/src/eviction/lru.rs
foyer-memory/src/eviction/s3fifo.rs
foyer-memory/src/handle.rs

test: include unwrap_unchecked into strict_assertions

---

foyer-intrusive/src/dlist.rs

fix: make DlistLink::raw mutable to try to fix a UB

---

foyer-memory/Cargo.toml
foyer-memory/src/generic.rs

test: refine fetch ut

---

Makefile
foyer-intrusive/src/dlist.rs
foyer-memory/src/generic.rs

refactor: remove unused in dlist, tighten fetch lock section

---

foyer-memory/src/generic.rs

test: add another fetch ut case

---

Cargo.toml
foyer-bench/Cargo.toml
foyer-bench/src/main.rs
foyer-common/Cargo.toml
foyer-util/Cargo.toml

chore: upgrade deps

---

foyer-memory/src/eviction/lru.rs
foyer-memory/src/generic.rs

fix: fix in-memory cache reinsertion metrics condition

---

foyer-memory/src/generic.rs

As title.
fix #528 
may be related with #525 #531

fix: fix dec ref overflow caused by clone inf ref

---

foyer-memory/src/cache.rs
foyer-memory/src/eviction/sanity.rs
foyer-memory/src/generic.rs

refactor: remove pop interface from the in-memory cache

---

Cargo.toml

As title.
https://github.com/instrumentisto/metrics-prometheus-rs/issues/10

fix: downgrade metrics to 0.22 to fix metrics

---

CHANGELOG.md
foyer-bench/Cargo.toml
foyer-common/Cargo.toml
foyer-intrusive/Cargo.toml
foyer-memory/Cargo.toml
foyer-storage/Cargo.toml
foyer/Cargo.toml

chore: relase foyer v0.9.1

---

foyer-bench/Cargo.toml
foyer-bench/src/main.rs

perf: support jemalloc for foyer bench

---

.github/template/template.yml
.github/workflows/main.yml
.github/workflows/pull-request.yml
Makefile
examples/Cargo.toml
examples/event_listener.rs
foyer-common/src/event.rs
foyer-common/src/lib.rs
foyer-memory/src/cache.rs
foyer-memory/src/generic.rs
foyer/src/hybrid/builder.rs
foyer/src/prelude.rs

feat: introduce new event listener abstraction

---

CHANGELOG.md
foyer-bench/Cargo.toml
foyer-common/Cargo.toml
foyer-intrusive/Cargo.toml
foyer-memory/Cargo.toml
foyer-storage/Cargo.toml
foyer/Cargo.toml

chore: release foyer 0.9.2

---

CHANGELOG.md
foyer-storage/Cargo.toml

chore: release foyer-storage 0.8.3

---

foyer-memory/src/cache.rs
foyer-memory/src/generic.rs
foyer-storage/src/large/generic.rs
foyer-storage/src/storage.rs
foyer-storage/src/store/mod.rs
foyer-storage/src/store/noop.rs
foyer-storage/src/store/runtime.rs
foyer/src/hybrid/cache.rs

perf: use dedicated runtime to fetch with hybrid cache

---

CHANGELOG.md
foyer-bench/Cargo.toml
foyer-common/Cargo.toml
foyer-intrusive/Cargo.toml
foyer-memory/Cargo.toml
foyer-storage/Cargo.toml
foyer/Cargo.toml

chore: release foyer v0.9.3

---

foyer-storage/src/large/reclaimer.rs
foyer-storage/src/large/recover.rs
foyer-storage/tests/storage_test.rs

fix: fix phantom entry after recovery by check sequence

---

CHANGELOG.md
foyer-bench/Cargo.toml
foyer-storage/Cargo.toml
foyer/Cargo.toml

chore: release foyer 0.9.4

---

foyer-bench/src/main.rs
foyer/src/hybrid/cache.rs

perf: add runtime switch to enable/disable tracing

---

Cargo.toml
foyer-bench/src/main.rs

As title. Use version >= 0.6.7, which contains some optimizations.

chore: switch minitrace to crates.io version

---

foyer-common/Cargo.toml
foyer-common/src/trace.rs
foyer-memory/Cargo.toml
foyer-memory/src/cache.rs
foyer-memory/src/generic.rs
foyer-storage/Cargo.toml
foyer-storage/src/device/direct_file.rs
foyer-storage/src/device/direct_fs.rs
foyer-storage/src/device/monitor.rs
foyer-storage/src/large/generic.rs
foyer-storage/src/large/indexer.rs
foyer-storage/src/store/mod.rs
foyer/Cargo.toml
foyer/src/hybrid/cache.rs

perf: add more minitrace spans

---

foyer/src/hybrid/cache.rs

fix: fix hybrid cache fetch span

---

foyer-memory/src/generic.rs
foyer/src/hybrid/cache.rs

refactor: refine tracing spans

---

docker-compose.yaml
foyer-bench/src/main.rs
foyer-common/src/lib.rs
foyer-common/src/tracing.rs
foyer/src/hybrid/builder.rs
foyer/src/hybrid/cache.rs
foyer/src/prelude.rs

refactor: rename TraceConfig to TracingConfig, udpate related API

---

.github/template/template.yml
.github/workflows/main.yml
.github/workflows/pull-request.yml
.typos.toml
Cargo.toml
Makefile
README.md
examples/Cargo.toml
examples/tail_based_tracing.rs

doc: add tail-based tracing example, update readme

---

README.md
examples/hybrid_full.rs
foyer-bench/src/main.rs
foyer-memory/Cargo.toml
foyer-memory/src/cache.rs
foyer-memory/src/generic.rs
foyer/Cargo.toml
foyer/src/hybrid/cache.rs

refactor: fetch no longer requires returned value with context

---

CHANGELOG.md
README.md
foyer-bench/Cargo.toml
foyer-common/Cargo.toml
foyer-intrusive/Cargo.toml
foyer-memory/Cargo.toml
foyer-storage/Cargo.toml
foyer/Cargo.toml

Release foyer 0.10.0. 
foyer 0.10 mainly focuses on the ability to observation like tail-based tracing.

chore: release foyer 0.10.0

---

README.md
examples/hybrid_full.rs
foyer-storage/src/large/flusher.rs
foyer-storage/src/large/generic.rs
foyer-storage/src/store/mod.rs
foyer-storage/src/store/runtime.rs
foyer/src/hybrid/builder.rs

As title. Any entries that exceeds the threshold will be ignored.
https://github.com/risingwavelabs/risingwave/issues/17591

feat: add disk cache flush buffer threshold

---

CHANGELOG.md
foyer-bench/Cargo.toml
foyer-common/Cargo.toml
foyer-intrusive/Cargo.toml
foyer-memory/Cargo.toml
foyer-storage/Cargo.toml
foyer/Cargo.toml

chore: release foyer 0.10.1

---

foyer-storage/src/engine.rs
foyer-storage/src/large/flusher.rs
foyer-storage/src/large/generic.rs
foyer-storage/src/large/recover.rs
foyer-storage/src/prelude.rs
foyer-storage/src/small/generic.rs
foyer-storage/src/small/mod.rs
foyer-storage/src/storage/either.rs
foyer-storage/src/storage/mod.rs
foyer-storage/src/storage/noop.rs
foyer-storage/src/storage/runtime.rs
foyer-storage/src/store.rs
foyer/src/prelude.rs

This PR is the first part to implement the combined (large + small) disk cache.
Changes:
- Introduced `Either` store.
- Refactored the relation between `Store` and `Storage`.
#596

feat: combined disk cache framework (p1)

---

foyer-common/src/event.rs
foyer-util/src/judge.rs

chore: remove some unused

---

foyer-storage/src/device/allocator.rs
foyer-storage/src/device/bytes.rs
foyer-storage/src/device/direct_file.rs
foyer-storage/src/device/direct_fs.rs
foyer-storage/src/device/mod.rs
foyer-storage/src/device/monitor.rs
foyer-storage/src/engine.rs
foyer-storage/src/large/flusher.rs
foyer-storage/src/large/generic.rs
foyer-storage/src/large/reclaimer.rs
foyer-storage/src/large/scanner.rs
foyer-storage/src/large/tombstone.rs
foyer-storage/src/prelude.rs
foyer-storage/src/region.rs
foyer-storage/src/serde.rs
foyer-storage/src/small/generic.rs
foyer-storage/src/storage/either.rs
foyer-storage/src/storage/mod.rs
foyer-storage/src/storage/noop.rs
foyer-storage/src/storage/runtime.rs
foyer-storage/src/store.rs

As title, something like `Bytes` and `BytesMut` but 4K-aligned.

feat: introduce 4K-aligned IoBytes and IoBytesMut

---

README.md

After https://github.com/chroma-core/chroma/pull/2431 is merged, [Chroma](https://github.com/chroma-core/chroma) is a foyer user now. 🥰

chore: add chroma to the showcase

---

foyer-storage/src/store.rs

chore: fix a rust docs

---

foyer-common/Cargo.toml
foyer-common/src/lib.rs
foyer-memory/src/indexer/sanity.rs
foyer-storage/src/serde.rs
foyer-util/src/lib.rs

refactor: fix warnings for toolchain 1.80

---

foyer-storage/src/large/batch.rs

refactor: tiny refine batch code

---

foyer-storage/src/store.rs
foyer-storage/tests/storage_test.rs
foyer/src/hybrid/cache.rs

refactor: move key comparison into foyer-storage

---

foyer-storage/src/engine.rs
foyer-storage/src/large/batch.rs
foyer-storage/src/large/flusher.rs
foyer-storage/src/large/generic.rs
foyer-storage/src/small/generic.rs
foyer-storage/src/storage/either.rs
foyer-storage/src/storage/mod.rs
foyer-storage/src/storage/noop.rs
foyer-storage/src/storage/runtime.rs
foyer-storage/src/store.rs
foyer/src/hybrid/cache.rs

fix: fix wait impl

---

foyer-storage/src/engine.rs
foyer-storage/src/large/batch.rs
foyer-storage/src/large/flusher.rs
foyer-storage/src/large/generic.rs
foyer-storage/src/large/reclaimer.rs
foyer-storage/src/prelude.rs
foyer-storage/src/small/generic.rs
foyer-storage/src/storage/either.rs
foyer-storage/src/storage/mod.rs
foyer-storage/src/storage/noop.rs
foyer-storage/src/storage/runtime.rs
foyer-storage/src/store.rs
foyer-storage/tests/storage_test.rs
foyer/src/hybrid/cache.rs
foyer/src/hybrid/writer.rs
foyer/src/prelude.rs

refactor: remove write handle for enqueue and delete

---

foyer-storage/src/large/recover.rs

As title.
https://github.com/risingwavelabs/risingwave/issues/18035
https://github.com/risingwavelabs/risingwave/pull/18036

fix: fix panic with none recover mode

---

CHANGELOG.md
foyer-bench/Cargo.toml
foyer-storage/Cargo.toml
foyer/Cargo.toml

fix: fix panic with none recover mode (#638)

---

CHANGELOG.md
foyer-bench/Cargo.toml
foyer-storage/Cargo.toml
foyer-storage/src/large/recover.rs
foyer/Cargo.toml

cherry-pick fix: fix panic with none recover mode (#638 #639)

---

foyer-storage/src/large/recover.rs

feat: add serde support for recover mode

---

CHANGELOG.md
foyer-bench/Cargo.toml
foyer-storage/Cargo.toml
foyer/Cargo.toml

chore: release foyer 0.10.3

---

CHANGELOG.md
foyer-bench/Cargo.toml
foyer-storage/Cargo.toml
foyer-storage/src/large/recover.rs
foyer/Cargo.toml

cherry-pick: feat: add serde support for recover mode (#641 #642)

---

examples/hybrid_full.rs
foyer-bench/src/main.rs
foyer-storage/src/store.rs

feat: support customize runtime max blocking threads

---

foyer-bench/src/main.rs

fix: fix foyer-bench recover mode

---

foyer-bench/src/main.rs

feat: support set foyer-bench worker threads

---

foyer-storage/src/device/direct_file.rs
foyer-storage/src/device/direct_fs.rs

perf: add O_NOATIME on linux

---

foyer-bench/src/main.rs
foyer-memory/Cargo.toml

As title.
https://github.com/MrCroxx/cmsketch-rs/pull/11

pref: reduce lfu cmsketch page fault

---

foyer-storage/src/store.rs

As title. Warp store field with `StoreInner`.

perf: reduce store clone overhead

---

foyer-storage/src/device/monitor.rs
foyer-storage/src/io_buffer_pool.rs
foyer-storage/src/large/generic.rs
foyer-storage/src/small/generic.rs

chore: fix license header

---

CHANGELOG.md
README.md
examples/Cargo.toml
foyer-bench/Cargo.toml
foyer-common/Cargo.toml
foyer-intrusive/Cargo.toml
foyer-memory/Cargo.toml
foyer-storage/Cargo.toml
foyer-util/Cargo.toml
foyer/Cargo.toml

doc: update readme

---

foyer-common/src/tracing.rs
foyer-storage/src/device/direct_file.rs
foyer-storage/src/device/direct_fs.rs
foyer-storage/src/store.rs

feat: support serde for more configs

---

foyer/src/prelude.rs

refactor: expose Weighter trait

---

.github/template/template.yml
.github/workflows/main.yml
.github/workflows/pull-request.yml
CHANGELOG.md
README.md
foyer-bench/Cargo.toml
foyer-common/Cargo.toml
foyer-intrusive/Cargo.toml
foyer-memory/Cargo.toml
foyer-storage/Cargo.toml
foyer/Cargo.toml

chore: release foyer 0.11.0

---

foyer-storage/src/store.rs

feat: impl Default for TokioRuntimeConfig

---

foyer-common/src/asyncify.rs
foyer-storage/Cargo.toml
foyer-storage/src/store.rs

fix: fix build with madsim

---

CHANGELOG.md
foyer-bench/Cargo.toml
foyer-common/Cargo.toml
foyer-intrusive/Cargo.toml
foyer-memory/Cargo.toml
foyer-storage/Cargo.toml
foyer/Cargo.toml

chore: release foyer 0.11.1

---

Cargo.toml
codecov.yml
foyer-cli/Cargo.toml
foyer-cli/src/args/error.rs
foyer-cli/src/args/fio.rs
foyer-cli/src/args/mod.rs
foyer-cli/src/main.rs

feat: introduce foyer-cli framework

---

foyer-common/src/code.rs
foyer-storage/src/serde.rs
foyer-storage/src/store.rs

perf: introduce size hint for storage key and value

---

README.md

chore: fix ci badge in readme

---

foyer/src/prelude.rs

As title.
for slatedb https://github.com/slatedb/slatedb

feat: expose in-memory cache builder and cache entry

---

CHANGELOG.md

doc: remove details tag in change log for better searching

---

CHANGELOG.md

chore: add some metadata for changelog

---

CHANGELOG.md

As title. Sorry, I'm debugging the document website....

chore: ignore changelog author details

---

README.md
foyer/src/lib.rs

chore: update badge with link

---

CHANGELOG.md
foyer-bench/Cargo.toml
foyer-common/Cargo.toml
foyer-intrusive/Cargo.toml
foyer-memory/Cargo.toml
foyer-storage/Cargo.toml
foyer/Cargo.toml

chore: relase foyer 0.11.3

---

foyer-storage/src/device/direct_file.rs

doc: fix a tiny broken link

---

foyer-storage/src/device/direct_file.rs

chore: warn if DirectFileDevice is used in a fs

---

CHANGELOG.md
foyer-bench/Cargo.toml
foyer-common/Cargo.toml
foyer-intrusive/Cargo.toml
foyer-memory/Cargo.toml
foyer-storage/Cargo.toml
foyer/Cargo.toml

chore: release foyer 0.11.4

---

CHANGELOG.md
foyer-bench/Cargo.toml
foyer-common/Cargo.toml
foyer-intrusive/Cargo.toml
foyer-memory/Cargo.toml
foyer-storage/Cargo.toml
foyer/Cargo.toml

chore: release foyer 0.11.5

---

.github/workflows/license_check.yml

chore: update license checker version

---

foyer-storage/src/large/batch.rs

bug: fix panic when serde as batching

---

CHANGELOG.md
foyer-common/src/runtime.rs
foyer-storage/src/runtime.rs

chore: fix typos with the lates typos checker

---

foyer-memory/src/cache.rs
foyer-memory/src/generic.rs

feat: scale shards to 1 when there is not enough capacity

---

CHANGELOG.md
Cargo.toml

chore: release 0.12.1

---

.github/workflows/ci.yml

chore: disable madsim test, just test build

---

CHANGELOG.md
Cargo.toml

chore: release foyer v0.12.2

---

Cargo.toml
foyer-bench/Cargo.toml
foyer-bench/src/main.rs
foyer-cli/Cargo.toml
foyer-cli/src/main.rs
foyer-common/src/lib.rs
foyer-intrusive/Cargo.toml
foyer-intrusive/src/lib.rs
foyer-memory/Cargo.toml
foyer-memory/benches/bench_dynamic_dispatch.rs
foyer-memory/benches/bench_hit_ratio.rs
foyer-memory/src/lib.rs
foyer-storage/src/lib.rs
foyer/Cargo.toml
foyer/src/lib.rs

refactor: use workspace lint rules for active crates

---

Cargo.toml
examples/Cargo.toml
foyer-bench/Cargo.toml

chore: update metrics and ot deps

---

foyer-storage/src/large/generic.rs

chore: add warning when region count is smaller than expected

---

examples/export_metrics_prometheus_hyper.rs
foyer-bench/src/main.rs
foyer/src/prelude.rs

To avoid conflict on multiple features enabled.
As title.

refactor: export metrics exporters in mod level

---

Makefile
README.md

chore: update "Other Examples" in readme

---

Cargo.toml
foyer-common/Cargo.toml
foyer-memory/Cargo.toml
foyer-storage/Cargo.toml
foyer/Cargo.toml

chore: upgrade hashbrown deps to 0.15

---

CHANGELOG.md
Cargo.toml
README.md
foyer-memory/Cargo.toml

chore: release foyer v0.13.0

---

Makefile
foyer-common/src/metrics/mod.rs
foyer-common/src/metrics/model.rs
foyer-common/src/metrics/registry/noop.rs
foyer-common/src/metrics/registry/opentelemetry_0_26.rs
foyer-common/src/metrics/registry/opentelemetry_0_27.rs
foyer-common/src/metrics/registry/prometheus.rs
foyer-common/src/metrics/registry/prometheus_client_0_22.rs
foyer-memory/src/cache.rs
foyer-storage/src/store.rs
foyer/src/hybrid/builder.rs

As title. Minor updates for semver.

refactor: use Cow<'static, str> instead of &'static str

---

CHANGELOG.md
Cargo.toml

chore: release foyer v0.13.1

---

.github/workflows/ci.yml

test(ci): temporarily disable lsan check

---

foyer-common/src/rate.rs
foyer-storage/src/large/batch.rs

As title. Prevent the bug from reappearing after 0.11
https://github.com/risingwavelabs/risingwave/issues/19945

test: add unit test to prevent batch insertion overflow

---

.github/workflows/ci.yml
Makefile
foyer-bench/Cargo.toml
foyer-common/Cargo.toml
foyer-memory/Cargo.toml
foyer-storage/Cargo.toml
foyer/Cargo.toml

As title. FYI: #824 
close #824

test: add cargo-machete test in make fast and ci

---

Cargo.toml
foyer-memory/src/eviction/test_utils.rs
foyer-memory/src/prelude.rs
foyer-memory/src/record.rs

refactor: simplify record, restrict record's visibility

---

.github/workflows/ci.yml

As title.
close #822 for it is no longer needed

test(ci): remove lsan alone test on CI, for asan already integrated it

---

Cargo.toml
foyer-common/Cargo.toml
foyer-common/src/metrics.rs

As title.
https://github.com/foyer-rs/mixtrics/issues/5
https://github.com/foyer-rs/mixtrics/pull/7

test: upgrade mixtrics, add metrics model test

---

CHANGELOG.md
Cargo.toml

chore: update deps and update changelog

---

.github/workflows/ci.yml
.typos.toml
Cargo.toml
Makefile
examples/Cargo.toml
foyer-bench/Cargo.toml
foyer-storage/Cargo.toml
foyer/Cargo.toml
rustfmt.nightly.toml
scripts/install-deps.sh

chore: format toml with taplo and check fmt on CI

---

CHANGELOG.md
Cargo.toml

chore: release foyer v0.14.0

---

.github/workflows/ci.yml

chore: enable CI on arm arch

---

Cargo.toml

chore: upgrade mixtrics to v0.0.3

---

.github/workflows/ci.yml

test: cache cargo udeps binary only for udeps test

---

Cargo.toml
foyer-bench/Cargo.toml
foyer-common/Cargo.toml
foyer-memory/Cargo.toml
foyer-storage/Cargo.toml
foyer/Cargo.toml

This closes https://github.com/foyer-rs/foyer/issues/852

deps: switch between tokio impls with cfg(madsim)

---

CHANGELOG.md
Cargo.toml

chore: release foyer v0.14.1

---

foyer-storage/src/large/batch.rs
foyer-storage/src/large/flusher.rs
foyer-storage/src/large/reclaimer.rs
foyer-storage/src/large/scanner.rs
foyer-storage/src/serde.rs
foyer-storage/src/small/batch.rs
foyer-storage/src/small/set.rs
foyer-storage/src/small/set_manager.rs

refactor: refine kv serde

---

foyer-common/src/tracing.rs
foyer/src/hybrid/cache.rs

This patch drop useless mut make clippy happy

fix: drop useless mut

---

foyer-storage/src/large/generic.rs
foyer-storage/src/serde.rs
foyer-storage/src/small/batch.rs
foyer-storage/src/small/set.rs

refactor: remove stale functions, refine error

---

foyer-common/src/metrics.rs
foyer-storage/src/small/generic.rs

feat: add disk cache load error metrics

---

README.md
foyer-storage/src/large/generic.rs

fix: fix missed load error metrics

---

README.md

doc: add new user dna

---

Cargo.toml
foyer-common/src/metrics.rs
foyer-storage/src/large/buffer.rs
foyer-storage/src/large/flusher.rs
foyer-storage/src/large/scanner.rs
foyer-storage/src/small/batch.rs

feat: enhance histogram precieseness, fix ser histogram

---

CHANGELOG.md
Cargo.toml
README.md

chore: release foyer v0.15.0

---

CHANGELOG.md
Cargo.toml

chore: release foyer v0.15.1

---

.github/workflows/ci.yml

As title. Let codecov merge the reports. Try it.
close #902

test: separate rust test and foyer bench test but merge codecov

---

foyer-storage/src/device/direct_file.rs
foyer-storage/src/device/direct_fs.rs
foyer-storage/src/error.rs
foyer-storage/src/large/generic.rs

refactor: mitigate low-pri errors, refine errors

---

CHANGELOG.md
Cargo.toml

chore: release foyer v0.15.2

---

foyer-storage/src/device/direct_fs.rs
foyer-storage/src/large/buffer.rs
foyer-storage/src/large/flusher.rs
foyer-storage/src/large/generic.rs

- Fix blob/region split condition calculation error.
- Add ut for the corner case.
- Refine splitter code.
- Fix direct fs error log.
close #905 
https://github.com/risingwavelabs/risingwave/pull/21116
https://github.com/risingwavelabs/risingwave/issues/21157

fix: fix split condition calculation error 

---

CHANGELOG.md
Cargo.toml

chore: release foyer v0.15.3

---

foyer-common/src/metrics.rs
foyer-storage/src/large/flusher.rs
foyer-storage/src/large/generic.rs
foyer-storage/src/small/flusher.rs

refactor: replace verbose channel overflow warn log with metrics

---

foyer-storage/src/store.rs

fix: fix build on the latest stabel toolchain

---

CHANGELOG.md
Cargo.toml
README.md
foyer/Cargo.toml

chore: release foyer v0.16.0

---

foyer-bench/src/analyze.rs
foyer-bench/src/main.rs
foyer-storage/src/device/mod.rs
foyer-storage/src/device/monitor.rs
foyer-storage/src/engine.rs
foyer-storage/src/large/flusher.rs
foyer-storage/src/large/generic.rs
foyer-storage/src/large/reclaimer.rs
foyer-storage/src/large/tombstone.rs
foyer-storage/src/picker/utils.rs
foyer-storage/src/prelude.rs
foyer-storage/src/small/flusher.rs
foyer-storage/src/small/generic.rs
foyer-storage/src/small/set_manager.rs
foyer-storage/src/statistics.rs
foyer-storage/src/storage/either.rs
foyer-storage/src/storage/mod.rs
foyer-storage/src/storage/noop.rs
foyer-storage/src/store.rs
foyer/src/hybrid/cache.rs
foyer/src/prelude.rs

refactor: unify `DeviceStats` and `Statistics`

---

foyer-storage/src/io/throttle.rs
foyer-storage/src/picker/utils.rs
foyer-storage/src/store.rs

As title.
TODO:
- ~How to deal with disk cache miss caused by read throttle?~
- ~Skip disk cache refill on cache miss caused by read throttle.~
UPDATE: Track the todos in a new issue. https://github.com/foyer-rs/foyer/issues/939
close #935

feat: impl disk cache read throttle by iops/throughput

---

foyer-common/src/lib.rs
foyer-common/src/location.rs
foyer-memory/src/cache.rs
foyer-memory/src/eviction/fifo.rs
foyer-memory/src/eviction/lfu.rs
foyer-memory/src/eviction/lru.rs
foyer-memory/src/eviction/s3fifo.rs
foyer-memory/src/pipe.rs
foyer-memory/src/raw.rs
foyer-memory/src/record.rs
foyer/src/hybrid/cache.rs
foyer/src/prelude.rs

feat: support set cache location, support Default/InMem for now

---

foyer-common/src/metrics.rs
foyer-memory/src/cache.rs
foyer-memory/src/prelude.rs
foyer-memory/src/raw.rs
foyer-storage/Cargo.toml
foyer-storage/src/lib.rs
foyer-storage/src/picker/utils.rs
foyer-storage/src/prelude.rs
foyer-storage/src/store.rs
foyer-storage/src/test_utils.rs
foyer-storage/tests/storage_fuzzy_test.rs
foyer/Cargo.toml
foyer/src/hybrid/cache.rs
foyer/src/prelude.rs

As title. FYI: #939 
close #939

feat: avoid disk cache write on disk cache miss by read throttled

---

foyer-storage/src/large/reclaimer.rs
foyer-storage/src/picker/mod.rs
foyer-storage/src/picker/utils.rs
foyer-storage/src/prelude.rs
foyer-storage/src/store.rs
foyer-storage/src/test_utils.rs
foyer/src/hybrid/writer.rs
foyer/src/prelude.rs

feat: make pick be aware of throttling

---

foyer-storage/src/large/flusher.rs
foyer-storage/src/lib.rs
foyer-storage/src/store.rs

fix: fix panic if buffer_pool_size / flushers is not 4K aligned

---

.github/workflows/ci.yml

test: run CI on release branches

---

.github/workflows/ci.yml

test: run CI on release branches (#950)

---

.github/workflows/license_check.yml

test: run license check on release branch

---

CHANGELOG.md
Cargo.toml

test: run CI on release branches (#950) (#951)

---

CHANGELOG.md
Cargo.toml

chore: bump foyer v0.16.1 (#954)

---

foyer-memory/src/cache.rs
foyer-memory/src/pipe.rs
foyer-memory/src/raw.rs
foyer-storage/src/store.rs
foyer/src/hybrid/builder.rs
foyer/src/hybrid/cache.rs

feat: support flush in-mem data to disk on hybrid cache close

---

Cargo.toml

chore: bump mixtrics to v0.1

---

foyer-common/src/location.rs
foyer-memory/src/cache.rs
foyer-memory/src/raw.rs
foyer-storage/src/store.rs
foyer/src/hybrid/cache.rs
foyer/src/hybrid/writer.rs

As title.
#927 , left discussion: Is it necessary to make popluated entry still follow the cache location advice?
close #928

feat: support OnDisk cache location advice

---

foyer-common/src/metrics.rs
foyer-storage/src/large/flusher.rs
foyer-storage/src/store.rs

feat: add metrics for lodc indexer insertion conflicts (#974)

---

CHANGELOG.md
Cargo.toml

test: run CI on release branches (#950) (#979)

---

CHANGELOG.md

chore: update changelog via #980

---

.github/workflows/ci.yml
Makefile
README.md
foyer-bench/Cargo.toml
foyer-common/Cargo.toml
foyer-common/src/lib.rs
foyer-memory/Cargo.toml
foyer-memory/src/cache.rs
foyer-memory/src/raw.rs
foyer-storage/Cargo.toml
foyer-storage/src/device/direct_file.rs
foyer-storage/src/device/direct_fs.rs
foyer-storage/src/device/monitor.rs
foyer-storage/src/large/generic.rs
foyer-storage/src/large/indexer.rs
foyer-storage/src/serde.rs
foyer/Cargo.toml
foyer/src/hybrid/builder.rs
foyer/src/hybrid/cache.rs
foyer/src/prelude.rs

refactor: opt out `fastrace` dep without feature `tracing`

---

foyer/src/hybrid/cache.rs

As the title.
close #964 again

feat: add builder for hybrid cache to make it easier to discover

---

CHANGELOG.md
Cargo.toml
README.md
foyer-storage/Cargo.toml

chore: release foyer v0.17.0

---

foyer-storage/src/serde.rs

fix: refine load out of range error handling

---

README.md

chore: add Percas to readme showcases

---

foyer-storage/src/device/mod.rs

refactor: impl PartialEq, Eq for Throttle, IopsCounter

---

.github/semantic.yml

chore: refine semantic config

---

CHANGELOG.md
Cargo.toml

chore: release foyer v0.17.1

---

CHANGELOG.md
Cargo.toml

chore: release foyer v0.17.2

---

foyer-memory/src/raw.rs

test: add ut for large entry insertion

---

examples/hybrid.rs
examples/hybrid_full.rs
examples/serde.rs
examples/tail_based_tracing.rs
foyer-bench/src/main.rs
foyer-storage/Cargo.toml
foyer-storage/src/store.rs
foyer-storage/tests/storage_fuzzy_test.rs
foyer/src/hybrid/builder.rs
foyer/src/hybrid/cache.rs

AS IS. Keep the building procedure consistent and clear.

refactor: refine disk cache engine builder

---

CHANGELOG.md
Cargo.toml

chore: release foyer v0.17.3

---

CHANGELOG.md
Cargo.toml

chore: bump foyer v0.17.3 (#1015)

---

.github/semantic.yml
Cargo.toml

chore: switch mixtrics to release v0.2.0

---

Cargo.toml
foyer-common/Cargo.toml
foyer-common/src/code.rs
foyer-common/src/hasher.rs
foyer-memory/Cargo.toml
foyer-memory/src/prelude.rs
foyer-memory/src/raw.rs
foyer-storage/src/large/generic.rs
foyer-storage/src/small/generic.rs
foyer-storage/src/storage/noop.rs
foyer-storage/src/store.rs
foyer-storage/tests/storage_fuzzy_test.rs
foyer/src/hybrid/cache.rs

Close #1018
FYI: https://github.com/foyer-rs/foyer/discussions/1010#discussioncomment-13593303
Need cherry pick to v0.17.x
close #1018

fix: use xxhash64 by default for consistent hash over runs

---

.github/workflows/ci.yml

ci: clear dir before each fuzzy test

---

CHANGELOG.md
Cargo.toml

chore: cherry pick release v0.17.4 changelog (#1032)

---

.github/workflows/ci.yml
CHANGELOG.md
Cargo.toml
Makefile
README.md
examples/Cargo.toml
examples/tail_based_tracing.rs
foyer-bench/Cargo.toml
foyer-common/Cargo.toml
foyer-memory/Cargo.toml
foyer-storage/Cargo.toml
foyer-storage/src/large/tombstone.rs
foyer/Cargo.toml

chore: refine dependencies and bump msrv to v1.82.0

---

foyer-storage/src/picker/utils.rs

chore: fix some tiny typos

---

foyer-storage/src/large/flusher.rs
foyer-storage/src/large/generic.rs
foyer-storage/src/large/indexer.rs
foyer-storage/src/large/reclaimer.rs

Fix phantom entry after removal.
FYI: https://github.com/apache/opendal/pull/6366/files#diff-f84e6246fd14176c17b1fe526f21f5549f2a904e8f6b5d227aab4cb0bf6a72eaR408
https://github.com/apache/opendal/pull/6366/files#diff-f84e6246fd14176c17b1fe526f21f5549f2a904e8f6b5d227aab4cb0bf6a72eaR408

fix: fix delete by recording tombstones in lodc indexer

---

foyer/src/hybrid/cache.rs

feat: impl auto close for hybrid cache

---

examples/hybrid_full.rs
foyer-bench/src/main.rs
foyer-storage/src/engine/large/engine.rs
foyer-storage/src/engine/large/eviction.rs
foyer-storage/src/engine/large/flusher.rs
foyer-storage/src/engine/large/indexer.rs
foyer-storage/src/engine/large/reclaimer.rs
foyer-storage/src/engine/large/recover.rs
foyer-storage/src/engine/large/region.rs
foyer-storage/src/engine/large/scanner.rs
foyer-storage/src/engine/large/tombstone.rs
foyer-storage/src/io/device/combined.rs
foyer-storage/src/io/device/file.rs
foyer-storage/src/io/device/fs.rs
foyer-storage/src/io/device/mod.rs
foyer-storage/src/io/device/noop.rs
foyer-storage/src/io/device/partial.rs
foyer-storage/src/io/engine/mod.rs
foyer-storage/src/io/engine/monitor.rs
foyer-storage/src/io/engine/noop.rs
foyer-storage/src/io/engine/psync.rs
foyer-storage/src/io/engine/uring.rs
foyer-storage/src/io/error.rs
foyer-storage/src/prelude.rs
foyer-storage/src/store.rs
foyer-storage/tests/storage_fuzzy_test.rs
foyer/src/hybrid/cache.rs
foyer/src/prelude.rs

refactor: introduce parition abstrction to device

---

foyer-bench/src/main.rs
foyer-storage/src/engine/large/engine.rs
foyer-storage/src/io/engine/uring.rs

feat: add iopoll for uring io engine and more tunable args

---

Cargo.toml
foyer-bench/src/main.rs
foyer-storage/Cargo.toml
foyer-storage/src/io/engine/uring.rs

feat: add more tuning args for uring engine

---

examples/Cargo.toml
foyer-bench/Cargo.toml
foyer-bench/src/main.rs

test: support adding latency for cache miss in foyer-bench

---

foyer-memory/src/cache.rs
foyer-memory/src/pipe.rs
foyer-memory/src/prelude.rs
foyer-memory/src/raw.rs
foyer-storage/Cargo.toml
foyer-storage/src/engine/large/engine.rs
foyer-storage/src/engine/large/flusher.rs
foyer-storage/src/engine/mod.rs
foyer-storage/src/engine/noop.rs
foyer-storage/src/keeper.rs
foyer-storage/src/lib.rs
foyer-storage/src/store.rs
foyer/src/hybrid/cache.rs

close #1036 
Duplicated with #1037 .
This PR doesn't require keys and values to be wrapped with `Arc`.
close #1036 
dup #1037

feat: introduce keeper to make disk cache write queue queryable

---

foyer-storage/src/engine/large/engine.rs
foyer-storage/src/engine/large/eviction.rs
foyer-storage/src/engine/large/region.rs
foyer-storage/src/engine/large/scanner.rs
foyer-storage/src/engine/large/tombstone.rs
foyer-storage/src/engine/mod.rs
foyer-storage/src/io/engine/mod.rs
foyer-storage/src/io/engine/monitor.rs
foyer-storage/src/io/engine/noop.rs
foyer-storage/src/io/engine/psync.rs
foyer-storage/src/io/engine/uring.rs
foyer-storage/src/store.rs

refactor: remove device dependency in io engine

---

CHANGELOG.md
Cargo.toml

fix: fix panic on decode corrupted header (#1097)

---

foyer-common/src/properties.rs

feat: support serde for properties

---

CHANGELOG.md
Cargo.toml

chore: release foyer v0.19.1

---

foyer-storage/src/store.rs

fix: fix is_noop() logic in store.rs (#1113)

---

CHANGELOG.md
Cargo.toml

chore: release foyer v0.19.2 

---

foyer/tests/hybrid_cache_fuzzy_test.rs

test: separate read and fetch in hybrid cache fuzzy test
